version: '3.4'

services:
  izicap.api:
    image: demo-token.jar:latest
    build:
      context: .
      dockerfile: izicap.api/Dockerfile
    ports:
      - "9090:8080"


  testauto.robot:
    image: izicapta/robotframework:latest
    build:
      context: .
      dockerfile: testauto.robot/Dockerfile
    environment:
      - api_endpoint=http://izicap.api
    depends_on:
      - izicap.api
networks:
    my-net:
      driver: bridge