version: '3.6'

services:
  izicap.api:
    image: izicap.api:latest
    build:
      context: .
      dockerfile: izicap.api/Dockerfile
    ports:
      - "9090:8080"


  izicapta_robotframework:
    image: izicapta_robotframework:latest
    build:
      context: .
      dockerfile: izicapta_robotframework/Dockerfile
    depends_on:
      - izicap.api
    command: sh -c "/wait && pabot --outputdir Results TestCases/"
    environment:
      - WAIT_HOSTS=izicap.api:9090
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

networks:
    my-net:
      driver: bridge